title: The Language of Art
description: >- # this means to ignore newlines until "baseurl:"
  A wiki to look over different art terms, and examples of each. Built by Tom Hackshaw.
baseurl: ""
url: "https://endoflife.date" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-timeago

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll_timeago:
  depth: 2
